- README.md
- package.json
- src/index.ts
> Fix badges

- README.md
- package.json
- src/index.ts
> Renaming enterprise to standard

- .github/CODEOWNERS
- .github/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
- remotemonitoring/armtemplates/basic-static-map.json
- remotemonitoring/armtemplates/basic.json
- remotemonitoring/scripts/all-in-one.yaml
- remotemonitoring/scripts/individual/auth.yaml
- remotemonitoring/scripts/individual/device-simulation.yaml
- remotemonitoring/scripts/individual/device-telemetry.yaml
- remotemonitoring/scripts/individual/iothub-manager.yaml
- remotemonitoring/scripts/individual/remote-monitoring-webui.yaml
- remotemonitoring/scripts/individual/storage-adapter.yaml
- remotemonitoring/scripts/individual/stream-analytics.yaml
- remotemonitoring/scripts/individual/ui-config.yaml
- remotemonitoring/single-vm/docker-compose.dotnet.yml
- remotemonitoring/single-vm/docker-compose.java.yml
- remotemonitoring/single-vm/scripts/logs.sh
- remotemonitoring/single-vm/scripts/simulate.sh
- remotemonitoring/single-vm/scripts/start.sh
- remotemonitoring/single-vm/scripts/stats.sh
- remotemonitoring/single-vm/scripts/status.sh
- remotemonitoring/single-vm/scripts/stop.sh
- remotemonitoring/single-vm/scripts/update.sh
- remotemonitoring/single-vm/setup.sh
1. Move files over from the “public tools” repo, which we can now delete
2. Change the URL of the VM setup script
3. Disable simulate.sh until we fix it
4. Update GitHub templates
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/azure/pcs-cli/173)
> Deploy “testing” images

- remotemonitoring/single-vm/scripts/simulate.sh
**Checklist:**
Fix for https://github.com/Azure/device-simulation-dotnet/issues/66 , simulate.sh now works
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/azure/pcs-cli/174)
> Update simulate.sh to bypass auth

- README.md
Just a quick one to align the convention used here with that used in /azure-iot-pcs-remote-monitoring-java. (Will need to ripple to dotnet version as well)
> Change the term "pre-configured" to "preconfigured"

- README.md
**Checklist:**
The current documentation isn't working for customers, revert to old instructions until npm package update is fixed.
> Update CLI README instructions until npm package issue updated

- .gitattributes
- .github/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
- .gitignore
- package-lock.json
- package.json
- remotemonitoring/scripts/all-in-one.yaml
- remotemonitoring/scripts/individual/auth.yaml
- remotemonitoring/scripts/individual/deployment-configmap.yaml
- remotemonitoring/scripts/individual/device-simulation.yaml
- remotemonitoring/scripts/individual/device-telemetry.yaml
- remotemonitoring/scripts/individual/iothub-manager.yaml
- remotemonitoring/scripts/individual/storage-adapter.yaml
- remotemonitoring/scripts/individual/stream-analytics.yaml
- remotemonitoring/scripts/individual/ui-config.yaml
- scripts/build
- scripts/clean-up
- src/k8smanager.ts
**Checklist:**
* Fix Standard deployment adding the missing env vars
* Remove old AAD vars not used
* Add scripts for building and cleaning up
* Review package.json, sync with az format
* Check in dependencies lock to track changes to dependencies
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/azure/pcs-cli/182)
> Add missing environment vars for auth and minor improvements to other areas

- src/deploymentmanager.ts
- src/index.ts
There was a typo in the code that was not creating the .kube directory in the user's home directory
**Checklist:**
> Create directory error

- remotemonitoring/armtemplates/basic-static-map.json
- remotemonitoring/armtemplates/basic.json
- remotemonitoring/armtemplates/standard-static-map.json
- remotemonitoring/armtemplates/standard.json
- remotemonitoring/scripts/all-in-one.yaml
- remotemonitoring/scripts/individual/auth.yaml
- remotemonitoring/scripts/individual/device-simulation.yaml
- remotemonitoring/scripts/individual/device-telemetry.yaml
- remotemonitoring/scripts/individual/iothub-manager.yaml
- remotemonitoring/scripts/individual/remote-monitoring-webui.yaml
- remotemonitoring/scripts/individual/storage-adapter.yaml
- remotemonitoring/scripts/individual/stream-analytics.yaml
- remotemonitoring/scripts/individual/ui-config.yaml
- remotemonitoring/single-vm/docker-compose.dotnet.yml
- remotemonitoring/single-vm/docker-compose.java.yml
Bumping the versions and tag for getting the cli for 1.0.0-preview.2 release
**Checklist:**
> Getting pcs-cli ready for 1.0.0-preview.2 release

- remotemonitoring/armtemplates/basic-static-map.json
- remotemonitoring/armtemplates/basic.json
- remotemonitoring/armtemplates/standard-static-map.json
- remotemonitoring/armtemplates/standard.json
- remotemonitoring/scripts/all-in-one.yaml
- remotemonitoring/scripts/individual/auth.yaml
- remotemonitoring/scripts/individual/device-simulation.yaml
- remotemonitoring/scripts/individual/device-telemetry.yaml
- remotemonitoring/scripts/individual/iothub-manager.yaml
- remotemonitoring/scripts/individual/remote-monitoring-webui.yaml
- remotemonitoring/scripts/individual/storage-adapter.yaml
- remotemonitoring/scripts/individual/stream-analytics.yaml
- remotemonitoring/scripts/individual/ui-config.yaml
- remotemonitoring/single-vm/docker-compose.dotnet.yml
- remotemonitoring/single-vm/docker-compose.java.yml
- remotemonitoring/single-vm/scripts/update.sh
- remotemonitoring/single-vm/setup.sh
Getting ready for 1.0.0-preview.2
**Checklist:**
> Adding the missing setup.sh changes

- .vscode/launch.json
- scripts/build
The build script added recently was calling the wrong command.
Also adjust the debugging settings to allow interactive sessions.
**Checklist:**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/azure/pcs-cli/197)
> Fix build script and debugging settings

- remotemonitoring/scripts/all-in-one.yaml
- remotemonitoring/single-vm/docker-compose.java.yml
Temporarily replace the Java Config microservice with the .NET one until some bugs are fixed
**Checklist:**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/azure/pcs-cli/199)
> Temporarily replace PCS config Java with the .NET equivalent

- remotemonitoring/scripts/all-in-one.yaml
- remotemonitoring/single-vm/docker-compose.java.yml
Temporary change
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/azure/pcs-cli/202)
> Change telemetry and storage to .NET

- remotemonitoring/scripts/all-in-one.yaml
- remotemonitoring/single-vm/docker-compose.java.yml
Use Telemetry Agent .NET
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/azure/pcs-cli/204)
> replace telemetry agent

- remotemonitoring/armtemplates/basic-static-map.json
- remotemonitoring/armtemplates/basic.json
- remotemonitoring/armtemplates/standard-static-map.json
- remotemonitoring/armtemplates/standard.json
- remotemonitoring/scripts/all-in-one.yaml
- remotemonitoring/scripts/individual/auth.yaml
- remotemonitoring/scripts/individual/device-simulation.yaml
- remotemonitoring/scripts/individual/device-telemetry.yaml
- remotemonitoring/scripts/individual/iothub-manager.yaml
- remotemonitoring/scripts/individual/remote-monitoring-webui.yaml
- remotemonitoring/scripts/individual/storage-adapter.yaml
- remotemonitoring/scripts/individual/stream-analytics.yaml
- remotemonitoring/scripts/individual/ui-config.yaml
- remotemonitoring/single-vm/docker-compose.dotnet.yml
- remotemonitoring/single-vm/docker-compose.java.yml
- remotemonitoring/single-vm/scripts/update.sh
- remotemonitoring/single-vm/setup.sh
Merging into release branch with tags for docker images updated to 1.0.0-preview.3
**Checklist:**
> Updating the docker tags to 1.0.0-preview.3 to get ready for public preview

- package.json
- remotemonitoring/armtemplates/basic-static-map.json
- remotemonitoring/armtemplates/basic.json
- remotemonitoring/armtemplates/standard-static-map.json
- remotemonitoring/armtemplates/standard.json
- remotemonitoring/scripts/all-in-one.yaml
- remotemonitoring/scripts/individual/auth.yaml
- remotemonitoring/scripts/individual/device-simulation.yaml
- remotemonitoring/scripts/individual/device-telemetry.yaml
- remotemonitoring/scripts/individual/iothub-manager.yaml
- remotemonitoring/scripts/individual/remote-monitoring-webui.yaml
- remotemonitoring/scripts/individual/storage-adapter.yaml
- remotemonitoring/scripts/individual/stream-analytics.yaml
- remotemonitoring/scripts/individual/ui-config.yaml
- remotemonitoring/single-vm/docker-compose.dotnet.yml
- remotemonitoring/single-vm/docker-compose.java.yml
- remotemonitoring/single-vm/scripts/update.sh
- remotemonitoring/single-vm/setup.sh
Bumping the version.
**Checklist:**
> 1.0.0-preview.3

- src/deploymentmanager.ts
Show exception message if deployment fails. Previous behavior was to show `Exception: ` and not include it.
**Checklist:**
> Show exception message if deployment fails

- package.json
Updating the inquirer library to latest to get the latest features and also the old version was causing a UI bug.
**Checklist:**
> Updating the inquirer library to latest

- solutions/devicesimulation-nohub/armtemplate/parameters.json
- solutions/devicesimulation/armtemplate/parameters.json
New "domain" and "subscriptionId" parameters used by the portal.  The values will be used later.
**Checklist:**
> Add new parameters to ARM template

- package.json
- src/k8smanager.ts
Type of change? 
* Cherry picking the commit that was done to preview.4 branch
* While running pcs command the remotemonitoring files were not being found because pcs was looking in cwd, so fixed to look into where the package is installed
* Bumping the cli version
**Checklist:**
> Fixing a bug that was not picking up the files from node modules

- solutions/remotemonitoring/single-vm/scripts/update.sh
- solutions/remotemonitoring/single-vm/setup.sh
Minor change to ensure local deployments work properly. Needed to update the REPOSITORY url.
...
**Checklist:**
> Updating path for REPOSITORY url

- package.json
Updating the version to latest
**Checklist:**
> Updating the package version to latest release

- package.json
Updating moments library version
**Checklist:**
> Updating the moment package version

- README.md
- package.json
- solutions/remotemonitoring/armtemplates/basic-parameters.json
- solutions/remotemonitoring/armtemplates/basic-static-map.json
- solutions/remotemonitoring/armtemplates/basic.json
- solutions/remotemonitoring/scripts/all-in-one.yaml
- solutions/remotemonitoring/single-vm/docker-compose.dotnet.yml
- solutions/remotemonitoring/single-vm/docker-compose.java.yml
- solutions/remotemonitoring/single-vm/scripts/update.sh
- solutions/remotemonitoring/single-vm/setup.sh
- src/config.ts
- src/deploymentmanager.ts
- src/index.ts
- src/k8smanager.ts
* With this change cli will replace the git tag and docker tag at runtime based on the current release version
* This change needs to be matched with aureiotsuite as well
**Checklist:**
> Making the release process more automated

- src/index.ts
Making the pcs -h text obvious for --versionOverride
**Checklist:**
> Changing the help text

- solutions/remotemonitoring/armtemplates/basic-parameters.json
- src/deploymentmanager.ts
Typo in name was preventing the deployment to go through.
**Checklist:**
> Fixing deployment error

- solutions/devicesimulation-nohub/armtemplate/template.json
- solutions/devicesimulation/armtemplate/template.json
Add a default value for deployment id parameter to fix deployment error from suite.
**Checklist:**
> add default deployment id

- package.json
- solutions/remotemonitoring/armtemplates/basic-static-map.json
- solutions/remotemonitoring/armtemplates/basic.json
- solutions/remotemonitoring/armtemplates/local.json
- solutions/remotemonitoring/armtemplates/standard-static-map.json
- solutions/remotemonitoring/armtemplates/standard.json
- src/deploymentmanager.ts
**Checklist:**
- [x ] All tests passed
> Add StreamAnalytics resource in ARM template

- package-lock.json
- package.json
- solutions/remotemonitoring/single-vm/scripts/update.sh
* Using -z option to check if the string is null or empty
* Also updated the typescript to latest stable version
**Checklist:**
> update script was failing to update because of string error

- solutions/remotemonitoring/armtemplates/basic-static-map.json
- solutions/remotemonitoring/armtemplates/basic.json
- solutions/remotemonitoring/armtemplates/local.json
- solutions/remotemonitoring/armtemplates/standard-static-map.json
- solutions/remotemonitoring/armtemplates/standard.json
* For ASA jobs to run without failing the default unit that we need is 3
* Fixed a typo in basis-static template
**Checklist:**
> Defaulting to higher streaming units and fixing a bug in basic-static

- solutions/remotemonitoring/armtemplates/basic.json
- solutions/remotemonitoring/armtemplates/standard.json
LocationBasedServices was deprecated, should be Maps
**Checklist:**
> Change LocationBasedServices to Map

- solutions/remotemonitoring/armtemplates/local.json
Adding Azure Maps resource for Local deployment types
**Checklist:**
> Adding azure maps for Local deployment type.

- src/deploymentmanager.ts
- src/index.ts
* Fix the bug of not including tenant id in resource group url for local
deployment
* Add a message to remind user to start streaming job for local
deployment
- [] New feature
...
**Checklist:**
> Add a reminder message to start streaming job for local deployment

- src/index.ts
In order for the user management service to easily identify the role of a user, we need to add a new [optional claim](ttps://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-optional-claims#configuring-optional-claims) in the AAD app manifest.
This will add roles information to the id token used for AAD:
(when unencoded):
Ex:
```
...
"family_name": "Bender",
"given_name": "Jill",
"name": "Jill Bender",
"roles": [
"Admin"
],
...
```
**Checklist:**
> Add optional claim to include user role in JWT id token

- .vscode/launch.json
- src/deploymentmanager.ts
- src/index.ts
> Service principal login option

- src/index.ts
> Assign admin role to the user who deploy the solution

- src/deploymentmanager.ts
Making the diagnosticsUrl optional and not add it in case of null value so that the default value from ARM template is picked up.
**Checklist:**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/azure/pcs-cli/317)
> Fixing the bug for making diagnosticsUrl optional

- .gitignore
- solutions/devicesimulation-nohub/single-vm/docker-compose.yml
- solutions/devicesimulation-nohub/single-vm/scripts/start.sh
- solutions/devicesimulation-nohub/single-vm/setup.sh
- solutions/devicesimulation-nohub/single-vm/setup/bashrc
- solutions/devicesimulation-nohub/single-vm/setup/init
- solutions/devicesimulation-nohub/single-vm/setup/nanorc
- solutions/devicesimulation/single-vm/docker-compose.yml
- solutions/devicesimulation/single-vm/scripts/start.sh
- solutions/devicesimulation/single-vm/setup.sh
- solutions/devicesimulation/single-vm/setup/bashrc
- solutions/devicesimulation/single-vm/setup/init
- solutions/devicesimulation/single-vm/setup/nanorc
Note: 
* deployment to be tested
* docs mentioning `docker-compose.yml` to be updated
1. Automatically start services in case of VM reboot
2. Allow to debug the start script in case of errors in the Docker Compose file (`start.sh --debug`)
3. Improve comments in docker-compose.yml and move comments at the start of the file
4. Some enhancements to the shell to improve UX when editing files in the VM
**Checklist:**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/azure/pcs-cli/318)
> VM fixes + improvements

- solutions/remotemonitoring/scripts/all-in-one.yaml
- solutions/remotemonitoring/scripts/individual/deployment-configmap.yaml
- solutions/remotemonitoring/scripts/individual/device-telemetry.yaml
- solutions/remotemonitoring/scripts/individual/iothub-manager.yaml
- solutions/remotemonitoring/scripts/individual/ui-config.yaml
- solutions/remotemonitoring/single-vm/docker-compose.dotnet.yml
- solutions/remotemonitoring/single-vm/docker-compose.java.yml
...
**Checklist:**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/azure/pcs-cli/312)
> Add service dependency on authentication service (hold on until role feature is completed)

- package-lock.json
- package.json
Fix known moderate severity vulnerability detected in static-eval < 2.0.0 defined in package-lock.json. 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/azure/pcs-cli/322)
> Fix security vulnerability 

- package-lock.json
- solutions/remotemonitoring/scripts/all-in-one.yaml
- solutions/remotemonitoring/scripts/individual/diagnostics.yaml
The standard deployment yaml had typo for diagnostics service
**Checklist:**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/azure/pcs-cli/325)
> Fixing a bug in standard deployment

- solutions/remotemonitoring/scripts/all-in-one.yaml
- solutions/remotemonitoring/scripts/individual/diagnostics.yaml
**Checklist:**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/azure/pcs-cli/327)
> Remove $ before docker tag

- package-lock.json
- package.json
Updating to the latest package version.
**Checklist:**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/azure/pcs-cli/336)
> Updating the package version

- solutions/devicesimulation-nohub/single-vm/docker-compose.yml
- solutions/devicesimulation/single-vm/docker-compose.yml
...
**Checklist:**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/azure/pcs-cli/339)
> adding diagnostics_webservice_url

- solutions/remotemonitoring/armtemplates/standard-parameters.json
- solutions/remotemonitoring/armtemplates/standard-static-map.json
- solutions/remotemonitoring/armtemplates/standard.json
- solutions/remotemonitoring/scripts/all-in-one.yaml
- solutions/remotemonitoring/scripts/individual/deployment-configmap.yaml
- solutions/remotemonitoring/scripts/individual/device-telemetry.yaml
- src/config.ts
- src/deploymentmanager.ts
- src/k8smanager.ts
...
**Checklist:**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/azure/pcs-cli/331)
> Add TSI support for standard version of remote monitoring

- src/deploymentmanager.ts
...
**Checklist:**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/azure/pcs-cli/343)
> Fix bug of using 'undefined' value of diagnosticsEdpointUrl

- solutions/remotemonitoring/armtemplates/basic-static-map.json
- solutions/remotemonitoring/armtemplates/basic.json
...
**Checklist:**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/azure/pcs-cli/346)
> Use Azure managed disk for VM OS disk

- solutions/devicesimulation-nohub/armtemplate/template.json
- solutions/devicesimulation/armtemplate/template.json
- solutions/remotemonitoring/armtemplates/basic-static-map.json
- solutions/remotemonitoring/armtemplates/basic.json
...
**Checklist:**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/azure/pcs-cli/347)
> Fix the default value of cloud type template parameter

- solutions/remotemonitoring/scripts/all-in-one.yaml
- solutions/remotemonitoring/single-vm/docker-compose.java.yml
...
**Checklist:**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/azure/pcs-cli/348)
> Use Java version for telemetry service in Java compose file

- solutions/remotemonitoring/armtemplates/basic-static-map.json
- solutions/remotemonitoring/armtemplates/basic.json
- solutions/remotemonitoring/armtemplates/local.json
- solutions/remotemonitoring/armtemplates/standard-static-map.json
- solutions/remotemonitoring/armtemplates/standard.json
- src/deploymentmanager.ts
- src/index.ts
* Use default location for TSI if it is not supported on selected
location
...
**Checklist:**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/azure/pcs-cli/351)
> Choose TSI location based on selected region

- solutions/remotemonitoring/armtemplates/basic-static-map.json
- solutions/remotemonitoring/armtemplates/basic.json
- solutions/remotemonitoring/armtemplates/standard-static-map.json
- solutions/remotemonitoring/armtemplates/standard.json
- src/deploymentmanager.ts
- src/index.ts
...
**Checklist:**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/azure/pcs-cli/352)
> Fix bug of DPS region support

- solutions/remotemonitoring/scripts/all-in-one.yaml
- solutions/remotemonitoring/scripts/individual/device-simulation.yaml
- solutions/remotemonitoring/single-vm/docker-compose.dotnet.yml
- solutions/remotemonitoring/single-vm/docker-compose.java.yml
...
**Checklist:**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/azure/pcs-cli/355)
> Use fixed version DS-1.0.2 for Device Simulation service

- solutions/remotemonitoring/armtemplates/basic-static-map.json
- solutions/remotemonitoring/armtemplates/basic.json
- solutions/remotemonitoring/armtemplates/local.json
- solutions/remotemonitoring/armtemplates/standard-static-map.json
- solutions/remotemonitoring/armtemplates/standard.json
...
**Checklist:**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/azure/pcs-cli/358)
> Use East US 2 as default region for TSI

- solutions/devicesimulation-nohub/single-vm/docker-compose.yml
- solutions/devicesimulation/single-vm/docker-compose.yml
Add env vars to compose file
**Checklist:**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/azure/pcs-cli/373)
> update docker compose files to use env vars

- solutions/remotemonitoring/armtemplates/local.json
- src/deploymentmanager.ts
...
**Checklist:**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/azure/pcs-cli/368)
> Output 'PCS_SEED_TEMPLATE' and diagnostics environment variables for local deployment

- src/index.ts
...
**Checklist:**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/azure/pcs-cli/374)
> Bug of latest version and TSI location value

- solutions/remotemonitoring/armtemplates/local.json
...
**Checklist:**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/azure/pcs-cli/377)
> Add missing DPS location parameter for local template

- package-lock.json
- package.json
This new version include 4 commits to hotfix ARM template bug
...
**Checklist:**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/azure/pcs-cli/378)
> Bump to version 1.0.11

- solutions/devicesimulation-nohub/single-vm/docker-compose.yml
- solutions/devicesimulation-nohub/single-vm/setup.sh
- solutions/devicesimulation/single-vm/docker-compose.yml
- solutions/devicesimulation/single-vm/setup.sh
- src/index.ts
Adding Seed_Template env variable
Updating max device count
SP should only be assigned contributor role on RG
..
**Checklist:**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/azure/pcs-cli/405)
> DS updates

- solutions/devicesimulation-nohub/single-vm/docker-compose.yml
- solutions/devicesimulation/single-vm/docker-compose.yml
* Update folder for logs.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/azure/pcs-cli/404)
> Update folder for logs

- solutions/remotemonitoring/scripts/all-in-one.yaml
- solutions/remotemonitoring/scripts/individual/ui-config.yaml
- solutions/remotemonitoring/single-vm/docker-compose.dotnet.yml
- solutions/remotemonitoring/single-vm/docker-compose.java.yml
- src/azurehelper.ts
- src/deploymentmanager.ts
* Remove the message of starting ASA job
* Save environment varibles into local file for local deployment
...
**Checklist:**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/azure/pcs-cli/402)
> Save environment variables into local file for local deployment (Issue #401)

- src/azurehelper.ts
...
**Checklist:**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/azure/pcs-cli/413)
> Ignore the error of contributor role assignment to unblock deployment

- solutions/remotemonitoring/armtemplates/basic-static-map.json
- solutions/remotemonitoring/armtemplates/basic.json
- solutions/remotemonitoring/armtemplates/local.json
- solutions/remotemonitoring/armtemplates/standard-static-map.json
- solutions/remotemonitoring/armtemplates/standard.json
...
**Checklist:**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/azure/pcs-cli/423)
> Change event source of TSI to IoTHub

- package-lock.json
Fixing security alert to bring the latest version of the dependency.
**Checklist:**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/azure/pcs-cli/428)
> Running npm audit fix

- docs/CONTRIBUTING.md
Our contribution guidelines are the stock guidelines without mention for testing all versions of the cli for deployments. This has lead to some features not being tested for local deployments for instance. 
This change updates the contribution guidelines to include deployments for all flavors as well as tests.
**Checklist:**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/azure/pcs-cli/433)
> Update CONTRIBUTING.md with local instructions

- solutions/devicesimulation-nohub/armtemplate/template.json
- solutions/devicesimulation-nohub/single-vm/docker-compose.yml
- solutions/devicesimulation/armtemplate/template.json
- solutions/devicesimulation/single-vm/docker-compose.yml
- src/index.ts
Updating templates for DS-2.0.1 release. 
This release will contain updated set up scripts along with some Simulation Service updates.
...
**Checklist:**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/azure/pcs-cli/435)
> Updates for DS-2.0.1 release

- solutions/remotemonitoring/single-vm/scripts/start.sh
- src/deploymentmanager.ts
- src/index.ts
* Because owner role assignment on subscription can not by done by using the token with AAD audience, this task is moved
from AAD application stage to deployment stage.
...
**Checklist:**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/azure/pcs-cli/437)
> Fix bug of standard deployment by service principal

- package.json
- src/index.ts
...
**Checklist:**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/azure/pcs-cli/439)
> Update release version and cli package version

- solutions/remotemonitoring/armtemplates/standard-static-map.json
- solutions/remotemonitoring/armtemplates/standard.json
...
**Checklist:**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/azure/pcs-cli/441)
> Bumping AKS to 1.11.5 

- solutions/devicesimulation-nohub/armtemplate/template.json
- solutions/devicesimulation/armtemplate/template.json
- src/index.ts
...
**Checklist:**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/azure/pcs-cli/447)
> Updating docker tags for DS-2.0.2 release

- package.json
- src/index.ts
Update version to 2.1.2
**Checklist:**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/azure/pcs-cli/448)
> Update version to 2.1.2

- solutions/remotemonitoring/armtemplates/basic-static-map.json
- solutions/remotemonitoring/armtemplates/basic.json
- solutions/remotemonitoring/armtemplates/local.json
- solutions/remotemonitoring/armtemplates/standard-static-map.json
- solutions/remotemonitoring/armtemplates/standard.json
- test/templates/test.json
...
**Checklist:**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/azure/pcs-cli/452)
> Update storage to use https communication

- src/deploymentmanager.ts
Add environment variables from set-env-uri script so that the user does not have to run set-env-uri script.
**Checklist:**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/azure/pcs-cli/453)
> Adding missing env vars

- src/deploymentmanager.ts
Adding missing env var.
**Checklist:**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/azure/pcs-cli/455)
> Adding another missing env var

- solutions/remotemonitoring/scripts/all-in-one.yaml
- solutions/remotemonitoring/scripts/individual/device-simulation.yaml
- solutions/remotemonitoring/single-vm/docker-compose.dotnet.yml
- solutions/remotemonitoring/single-vm/docker-compose.java.yml
This PR goes alongside https://github.com/Azure/device-simulation-dotnet/pull/337 to update Remote Monitoring to Device Simulation release DS-1.0.3. This change includes User Agent tagging on top of the stable version DS-1.0.2.
**Checklist:**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/azure/pcs-cli/454)
> Upgrade Remote Monitoring to DS-1.0.3

- package.json
- src/index.ts
Release 2.1.3
...
**Checklist:**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/azure/pcs-cli/458)
> Release 2.1.3

- solutions/remotemonitoring/single-vm/setup.sh
The goal behind this change is to get the scripts identical to DS when it comes to installing Docker. There were some options in apt-get that might work better to allow upgrades and downgrades. We will monitor the success rate to see if this actually makes any difference.
**Checklist:**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/azure/pcs-cli/467)
> Making the setup script similar to the DS

- solutions/remotemonitoring/armtemplates/standard-parameters.json
- solutions/remotemonitoring/scripts/all-in-one.yaml
- solutions/remotemonitoring/scripts/individual/deployment-configmap.yaml
- solutions/remotemonitoring/scripts/individual/device-simulation.yaml
- solutions/remotemonitoring/scripts/individual/diagnostics.yaml
- solutions/remotemonitoring/single-vm/docker-compose.dotnet.yml
- solutions/remotemonitoring/single-vm/docker-compose.java.yml
- src/config.ts
- src/deploymentmanager.ts
- src/index.ts
- src/k8smanager.ts
Adding AppInsights Instrumentation Key env Variable for Diagnostics MS
...
**Checklist:**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/azure/pcs-cli/468)
> Adding AppInsights Instrumentation Key env Variable for Diagnostics MS

- package.json
- src/index.ts
Updating tags for 2.2.0 release
**Checklist:**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/azure/pcs-cli/469)
> Release 2.2.0

- solutions/remotemonitoring/armtemplates/standard.json
- solutions/remotemonitoring/single-vm/setup.sh
The version for AKS is not longer available. So adding the versions that are available. 
Long term fix would be to call AKS get valid set of version and use the latest one.
**Checklist:**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/azure/pcs-cli/472)
> Updating the AKS orchsetrator version

- solutions/remotemonitoring/scripts/all-in-one.yaml
- solutions/remotemonitoring/scripts/individual/diagnostics.yaml
- solutions/remotemonitoring/single-vm/docker-compose.dotnet.yml
- solutions/remotemonitoring/single-vm/docker-compose.java.yml
Pointing to Diagnostics 2.0.1 after changing env var in diagnostics service.
**Checklist:**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/azure/pcs-cli/475)
> Diagnostics-2.0.1

- package.json
There is a bug in RM npm version 2.2.0 and after the fix npm doesn't allow us to use the same version number again, so I'm incrementing version number to 2.2.1 
**Checklist:**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/azure/pcs-cli/478)
> Incrementing npm version to 2.2.1

- package-lock.json
- solutions/remotemonitoring/armtemplates/basic-parameters.json
- solutions/remotemonitoring/armtemplates/basic-static-map.json
- solutions/remotemonitoring/armtemplates/basic.json
- solutions/remotemonitoring/armtemplates/keyvault-parameters.json
- solutions/remotemonitoring/armtemplates/keyvault.json
- solutions/remotemonitoring/scripts/all-in-one.yaml
- solutions/remotemonitoring/single-vm/docker-compose.dotnet.yml
- solutions/remotemonitoring/single-vm/docker-compose.java.yml
- solutions/remotemonitoring/single-vm/scripts/auth.sh
- solutions/remotemonitoring/single-vm/scripts/start.sh
- solutions/remotemonitoring/single-vm/scripts/update.sh
- solutions/remotemonitoring/single-vm/setup.sh
- src/deploymentmanager.ts
- src/index.ts
Move VM provisioning to take a dependency on keyvault being available. Some other small additional fixes such as corsWhitelist and enabling diagnostics profile.
**Checklist:**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/azure/pcs-cli/489)
> VM Provisioning fix for KeyVault

- solutions/devicesimulation-nohub/single-vm/docker-compose.yml
- solutions/devicesimulation/single-vm/docker-compose.yml
Update tag to to Diagnostics-2.0.1
**Checklist:**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/azure/pcs-cli/495)
> Update tag 

- package-lock.json
- package.json
Fix for this issue -> https://github.com/Azure/pcs-cli/issues/494
...
**Checklist:**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/azure/pcs-cli/500)
> Fix for npm vulnerabilities

- package.json
- src/index.ts
3.0.0 release for RM.
- Release
**Checklist:**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/azure/pcs-cli/505)
> CLI release for RM 3.0.0

- solutions/remotemonitoring/scripts/individual/device-simulation.yaml
- solutions/remotemonitoring/scripts/individual/diagnostics.yaml
Outdated version on DS yaml file for RM.
**Checklist:**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/azure/pcs-cli/506)
> Move DS to 1.0.5 for RM

- package.json
Bump version to 3.0.1 in npm to push vm script extension fix.
**Checklist:**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/azure/pcs-cli/508)
> Update npm package to 3.0.1

- solutions/remotemonitoring/armtemplates/basic.json
Basic deployment is failing as VM sku for Standard D1_V1 has changed to DS1_v2. 
- [] New feature
**Checklist:**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/azure/pcs-cli/518)
> VM sku change

- solutions/devicesimulation-nohub/armtemplate/template.json
- solutions/devicesimulation/armtemplate/template.json
Updating the docker tags for Simulation releases. 
**Checklist:**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/azure/pcs-cli/526)
> Updating docker tag for Simulation to DS-2.0.5

- solutions/remotemonitoring/armtemplates/basic-static-map.json
- solutions/remotemonitoring/armtemplates/basic.json
- solutions/remotemonitoring/armtemplates/standard-static-map.json
- solutions/remotemonitoring/armtemplates/standard.json
Added the latest VM size that works as default in all the Azure regions.
**Checklist:**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/azure/pcs-cli/528)
> Updating the default VM
