Azure/pcs-cli

remotemonitoring/scripts/all-in-one.yaml, remotemonitoring/single-vm/docker-compose.java.yml
The hubmanager java microservice has several bugs blocking critical functionality. Fixes are currently in progress, but may take a while. Until those are fixed we can move the java deployment to use the .Net service. 
**Checklist:**
=> Temporarily change iothub-manager-java to iot-hub-manager-dotnet in Java deployment

remotemonitoring/armtemplates/basic-static-map.json, remotemonitoring/armtemplates/basic.json, remotemonitoring/armtemplates/standard-static-map.json, remotemonitoring/armtemplates/standard.json
Fix for https://github.com/Azure/pcs-cli/issues/200
1. Link the existing Network Security Group to the existing Network Controller Interface, so that network security rules can be applied.
2. Remove dependency of web app on public IP, not required for the deployment, the app is stateless and start working as soon as the IP is available, there is no need to wait
3. Disable client affinity, not required for stateless web applications.
**Checklist:**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/azure/pcs-cli/218)
=> Link network security group to network controller interface

src/deployui.ts
**Checklist:**
Added convenience of seeing exact elapsed time instead of having to use a separate timer or wait until deployment completes before getting a time check.
=> Add elapsed time to bottom bar, will show when operation status is available

remotemonitoring/armtemplates/basic-static-map.json, remotemonitoring/armtemplates/basic.json
Even if port 22 is closed by default, having an explicit rule makes it easier to open/close the port for debugging
**Checklist:**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/azure/pcs-cli/229)
=> Add rule to explicitly block port 22

remotemonitoring/single-vm/scripts/start.sh, remotemonitoring/single-vm/setup.sh
When the services start in the basic deployment, a nohup.out file is created.  Since the file includes the output, possibly the logs, it will impact the service perf and potentially fill the disk.
**Checklist:**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/azure/pcs-cli/230)
=> Disable the creation of nohup.out file

package.json
Missing pre-req dependencies in https://github.com/Azure/pcs-cli/issues/240
- [X ] Bug fix
Bug fix for https://github.com/Azure/pcs-cli/issues/240
Adding missing npm package dependencies that were causing pcs login to fail.
"adal-node": "0.1.26",
"azure-arm-authorization": "4.1.0", 
"azure-arm-compute": "4.0.0", 
"azure-arm-website": "2.0.0-preview"
**Checklist:**
=> Fix failures in pcs login due to package.json

.vscode/launch.json, remotemonitoring/armtemplates/standard-static-map.json, remotemonitoring/armtemplates/standard.json, src/deploymentmanager.ts, src/index.ts
* Added a feature that allows user to specify service principal and secret through command line arguments
* For standard deployment if the user doesn't have owner access to subscription then they can't deploy, this change will allow admin/owner to provide a pre created service principal with contributor access and then user can deploy even if they have contributor role
**Checklist:**
=> Allowing user to specify service principal and secret

solutions/remotemonitoring/single-vm/docker-compose.dotnet.yml, solutions/remotemonitoring/single-vm/docker-compose.java.yml
The docker0 interface does not allow for filters to be applied and
containers on the network are vulnerable to ARP spoofing and MAC
flooding attacks. Create and setup 'default_net' network and bind all
containers to the defined network to avoid this issue.
PBI[2211813]
...
**Checklist:**
=> Define network for docker compose and bind to all containers

solutions/remotemonitoring/single-vm/docker-compose.dotnet.yml, solutions/remotemonitoring/single-vm/docker-compose.java.yml, solutions/remotemonitoring/single-vm/setup.sh
The API gateway should use non-root user for nginx service. The listening port must be above 1024 for non-root user.
**Checklist:**
=> Change to use 10080/10443 port in API gateway and add read permission on certs volume

solutions/remotemonitoring/single-vm/setup.sh
PBI[2211819]
The current configuration potentially allows for communications compromise by attackers, including decryption of traffic and secret key recovery. There are known attacks targeting some of these configuration parameters. Tightening the sshd configuration will harden the servers by reducing the attack surface.
**Checklist:**
=> Harden ssh config to avoid using weak HostKeys, algorithms, Ciphers and MACs

solutions/devicesimulation/single-vm/setup.sh
Fix url used in setup script for deployments (with hub)
**Checklist:**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/azure/pcs-cli/319)
=> Fix url used for deployments with hub

solutions/devicesimulation-nohub/armtemplate/template.json, solutions/devicesimulation-nohub/single-vm/setup.sh, solutions/devicesimulation/armtemplate/template.json
Revert back to using documentDBName param name instead of cosmosDbSqlName 
**Checklist:**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/azure/pcs-cli/369)
=> Revert to param name documentDBName

src/deploymentmanager.ts
* SFTP client sometimes failed to download credentials within max
retries. This might caused by the delay of K8S cluster spinning up.
Increasing max retries will increase the chance to succeed.
...
**Checklist:**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/azure/pcs-cli/366)
=> Increase retries for SFTP client to download credentials

solutions/remotemonitoring/scripts/all-in-one.yaml, solutions/remotemonitoring/scripts/individual/asa-manager.yaml
...
**Checklist:**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/azure/pcs-cli/412)
=> Fix bug of missing environment varialbes 'TELEMETRY_STORAGE_TYPE' in K8S

solutions/remotemonitoring/armtemplates/basic-static-map.json, solutions/remotemonitoring/armtemplates/basic.json, solutions/remotemonitoring/armtemplates/local.json, solutions/remotemonitoring/armtemplates/standard-static-map.json, solutions/remotemonitoring/armtemplates/standard.json
In order for emails to be sent with formatting, we need to enable HTML on the Logic App Connector.
**Checklist:**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/azure/pcs-cli/421)
=> Enable HTML in the O365 Logic App connector for Email Actions

solutions/devicesimulation-nohub/single-vm/setup-wrapper.sh, solutions/devicesimulation/single-vm/setup-wrapper.sh, solutions/remotemonitoring/single-vm/setup-wrapper.sh
Including this call to 'cat' in these scripts goes against the purpose of the setup-wrapper.sh script, which moves error logs potentially containing secrets to the output file in order to prevent those secrets being exposed and captured by the backend of the deployment process.
**Checklist:**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/azure/pcs-cli/434)
=> Remove call to 'cat' which can expose secrets on failure

package-lock.json, package.json
PCS script hang with node version 10.13.0 because inquirer library did not return from creating prompt.
Fixed by using the latest inquirer library.
Tested both v8.12.0 and 10.13.0
**Checklist:**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/azure/pcs-cli/438)
=> fix script hang issue with node v10.13.0

src/deploymentmanager.ts
Local deployment from CLI failed on run-time because of wrong environment variables.
There were two issues.
1. executing multiple setx commands joined by new line failed. 
2. PCS_DIAGNOSTICS_ENDPOINT_URL did not have value so that it was syntax error.
Fix:
1. adding default value for diagnostics endpoint environment variable
2. execute setx command individually and if command fails, catch an error and print error message to console.
**Checklist:**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/azure/pcs-cli/449)
=> fix failing local deployment on run time due to environment variables

solutions/remotemonitoring/single-vm/setup.sh
Fix for: https://github.com/Azure/pcs-cli/issues/482  
The [CustomScript](https://github.com/Azure/pcs-cli/blob/master/solutions/remotemonitoring/single-vm/setup.sh) for the VMExtension currently calls:
```
apt-get update -o Acquire::CompressionTypes::Order::=gz \
&& apt-get upgrade -y \
&& apt-get update \
```
This unknowlingly triggers an upgrade for WALinuxAgent and waits for the completion of this operation. Since WALinuxAgent is waiting for the extensions to finish running before terminating, this becomes a circular dependency. The dependency causes the CustomScript to time out after 90 minutes and the deployment fails.
This issue came to light only since Ubuntu 1604 updated the walinuxagent package in their repo:
http://changelogs.ubuntu.com/changelogs/pool/main/w/walinuxagent/walinu …
=> Blacklist walinuxagent in VM Extensions CustomScript

solutions/remotemonitoring/single-vm/setup.sh
The package console-setup tries to prompt user for an encoding. The package seems to be unnecessary so we can simply mark it as held to not install it.
**Checklist:**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/azure/pcs-cli/507)
=> VM timeout caused by console-setup

solutions/remotemonitoring/armtemplates/basic-static-map.json, solutions/remotemonitoring/armtemplates/basic.json
Remote Moniotoring deployments for the australiaeast and the australiaaoutheast regions were hitting an error on the TSI allowed values part of the ARM template.
TSI now supports australiaeast and australiasoutheast which was showing up as a new option for azureiotsolutions.com due to a dynamic region check. This change removes the hardcoded allowed values in the ARM template for basic deployments. By removing the hardcoded allowed regions, we can rely on the dynamic API call to return a list of allowed regions instead. `provisioningServiceLocation` could hit the same issue so the allowed values in the template have also been removed.
**Checklist:**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …
=> Remove hardcoded allowed values for TSI and Provisioning in ARM templates
